name: Release

on:
  push:
    branches: main
    
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          nix build .#resume 
          cp -L result resume.pdf
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v0.0.${{ github.run_number }}" -m "Release v0.0.${{ github.run_number }}"
          git push origin "v0.0.${{ github.run_number }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.${{ github.run_number }}
          files: resume.pdf
